### ISSUE TITLE
Would like to add a texture

### ISSUE THREAD

**Issue by jarodium** [holgerl/procedural-planet#3]
Hello

I would like to add a texture from an image. This would be great since I would like to create stars and alien worlds based on textures.

**Comment by holgerl** [comment]
Hi!

Even though using textures might seem as a small change to the code, it actually means doing things in a completely different way. This is because the code now is focused on how to achieve the planet by using custom shaders, and this was the main motivation for creating this repo and the associated article.

So to achieve what you want, I would rather google making textured spheres in Three.js. And then use a sphere for the planet and a bigger sphere for the star sky around it.
